# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fmr_pb2 as fmr_dot_fmr__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fmr/fmr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FmrServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeGpsInfo = channel.unary_stream(
                '/mavsdk.rpc.fmr.FmrService/SubscribeGpsInfo',
                request_serializer=fmr_dot_fmr__pb2.SubscribeGpsInfoRequest.SerializeToString,
                response_deserializer=fmr_dot_fmr__pb2.GpsInfoResponse.FromString,
                _registered_method=True)
        self.SetRateGpsInfo = channel.unary_unary(
                '/mavsdk.rpc.fmr.FmrService/SetRateGpsInfo',
                request_serializer=fmr_dot_fmr__pb2.SetRateGpsInfoRequest.SerializeToString,
                response_deserializer=fmr_dot_fmr__pb2.SetRateGpsInfoResponse.FromString,
                _registered_method=True)


class FmrServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeGpsInfo(self, request, context):
        """Subscribe to 'GPSInfo' updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRateGpsInfo(self, request, context):
        """Set rate to 'GpsInfo' updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FmrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeGpsInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeGpsInfo,
                    request_deserializer=fmr_dot_fmr__pb2.SubscribeGpsInfoRequest.FromString,
                    response_serializer=fmr_dot_fmr__pb2.GpsInfoResponse.SerializeToString,
            ),
            'SetRateGpsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRateGpsInfo,
                    request_deserializer=fmr_dot_fmr__pb2.SetRateGpsInfoRequest.FromString,
                    response_serializer=fmr_dot_fmr__pb2.SetRateGpsInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mavsdk.rpc.fmr.FmrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mavsdk.rpc.fmr.FmrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FmrService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeGpsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mavsdk.rpc.fmr.FmrService/SubscribeGpsInfo',
            fmr_dot_fmr__pb2.SubscribeGpsInfoRequest.SerializeToString,
            fmr_dot_fmr__pb2.GpsInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRateGpsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mavsdk.rpc.fmr.FmrService/SetRateGpsInfo',
            fmr_dot_fmr__pb2.SetRateGpsInfoRequest.SerializeToString,
            fmr_dot_fmr__pb2.SetRateGpsInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
